GET http://127.0.0.1:5001/greenguardian-app/us-central1/api

###
POST  http://127.0.0.1:5001/greenguardian-app/us-central1/api
Content-Type: application/json
{
    "name": "Shay A"
    "mail": "zzzz9529@gmail.com"
}

###
DELETE  http://127.0.0.1:5001/greenguardian-app/us-central1/api

###
PUT http://127.0.0.1:5001/greenguardian-app/us-central1/api
